global:
  scrape_interval: 15s

rule_files:
  - "/etc/prometheus/rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "nginx"
    static_configs:
      - targets: ["nginx-exporter:9113"]

  - job_name: "clickhouse"
    static_configs:
      - targets: ["clickhouse:9363"]

  - job_name: "elasticsearch"
    static_configs:
      - targets: ["elasticsearch-exporter:9114"]

  - job_name: "haproxy"
    static_configs:
      - targets: ["haproxy:8404"]
