services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    ports:
      - "9090:9090"

  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter
    ports:
      - "9113:9113"
    command: ["-nginx.scrape-uri", "http://nginx:8080/stub_status"]

  clickhouse:
    image: clickhouse/clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse-data:/var/lib/clickhouse

  clickhouse-exporter:
    image: flant/clickhouse-exporter
    environment:
      - CLICKHOUSE_EXPORTER_WEB_LISTEN_ADDRESS=:9116
      - CLICKHOUSE_EXPORTER_CLICKHOUSE_ADDR=http://clickhouse:8123
      - CLICKHOUSE_EXPORTER_CLICKHOUSE_USER=default
      - CLICKHOUSE_EXPORTER_CLICKHOUSE_PASSWORD=
    ports:
      - "9116:9116"

volumes:
  clickhouse-data:
