services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    ports:
      - "9090:9090"

  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter
    ports:
      - "9113:9113"
    command: ["-nginx.scrape-uri", "http://nginx:8080/stub_status"]

  clickhouse:
    image: clickhouse/clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9363:9363"
    volumes:
      - clickhouse-data:/var/lib/clickhouse
      - ./config.xml:/etc/clickhouse-server/config.d/config.xml

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.1
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es-data:/usr/share/elasticsearch/data

  elasticsearch-exporter:
    image: prometheuscommunity/elasticsearch-exporter
    ports:
      - "9114:9114"
    environment:
      - ES_URI=http://elasticsearch:9200
      - ES_ALL=true

volumes:
  clickhouse-data:
  es-data:
